// <auto-generated />
using CampusDash.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260207172523_SeedCustomers")]
    partial class SeedCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CampusDash.Backend.Models.Customer", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Email = "rowdy.1@wright.edu",
                            Active = true,
                            FirstName = "Rowdy",
                            Id = 1,
                            LastName = "Raider",
                            Latitude = 39.781100000000002,
                            Longitude = -84.064499999999995,
                            Password = "HashedPassword123"
                        },
                        new
                        {
                            Email = "engineer.2@wright.edu",
                            Active = true,
                            FirstName = "Alice",
                            Id = 2,
                            LastName = "Engineer",
                            Latitude = 39.771500000000003,
                            Longitude = -84.063000000000002,
                            Password = "HashedPassword456"
                        },
                        new
                        {
                            Email = "developer.3@wright.edu",
                            Active = true,
                            FirstName = "Bob",
                            Id = 3,
                            LastName = "Developer",
                            Latitude = 39.783000000000001,
                            Longitude = -84.0655,
                            Password = "HashedPassword789"
                        });
                });

            modelBuilder.Entity("CampusDash.Backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CustLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CustLong")
                        .HasColumnType("REAL");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DLat")
                        .HasColumnType("REAL");

                    b.Property<double>("DelivaryManLong")
                        .HasColumnType("REAL");

                    b.Property<int>("Otp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StoreLat")
                        .HasColumnType("REAL");

                    b.Property<double>("StoreLong")
                        .HasColumnType("REAL");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
